import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,mkdir,readFile,readdir,rm,symlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {buildWeb} from './build-web.mjs';import {createStaticHandler} from './serve-web.mjs';import {dataset,entry} from './web-fixtures.mjs';
test('build copies only public assets, relative paths and shards, refuses overwrite',async()=>{const dir=await mkdtemp(join(tmpdir(),'web-build-'));try{const input=join(dir,'in');await mkdir(input);await writeFile(join(input,'dictionary.json'),JSON.stringify(dataset([entry('かな')])));await writeFile(join(input,'archive.jsonl'),'');await writeFile(join(input,'secret.txt'),'not public');const out=join(dir,'out');const {version}=await buildWeb(input,out);const html=await readFile(join(out,'index.html'),'utf8');assert.match(html,/\.\/web\/app.mjs/);assert.ok(html.includes('./data/'+version+'/manifest.json'));assert.ok(!html.includes('__MANIFEST_URL__'));assert.deepEqual((await readdir(out)).sort(),['.nojekyll','ATTRIBUTION.txt','build-info.json','data','dictionary.mjs','index.html','reading-bucket.mjs','web']);assert.deepEqual((await readdir(join(out,'web'))).sort(),['app.mjs','battle-app.mjs','battle-controller.mjs','battle-rules.mjs','candidate-groups.mjs','dictionary-client.mjs','meaning-equivalences.mjs','styles.css']);await assert.rejects(buildWeb(input,out),/exist/);}finally{await rm(dir,{recursive:true,force:true})}});
test('static handler serves output only and blocks traversal, symlink and malformed paths',async()=>{const dir=await mkdtemp(join(tmpdir(),'web-serve-'));try{const out=join(dir,'out');await mkdir(out);await writeFile(join(out,'index.html'),'safe');await writeFile(join(dir,'secret.txt'),'secret');await symlink(join(dir,'secret.txt'),join(out,'leak.txt'));const handler=await createStaticHandler(out);async function request(url,method='GET'){let status,body;await handler({url,method},{writeHead(s){status=s},end(b){body=b?.toString()}});return {status,body};}assert.deepEqual(await request('/'),{status:200,body:'safe'});for(const p of ['/..%2fsecret.txt','/leak.txt','/%zz'])assert.notEqual((await request(p)).status,200);assert.equal((await request('/missing')).status,404);assert.equal((await request('/','POST')).status,405);}finally{await rm(dir,{recursive:true,force:true})}});

test('packaging rejects stale copied source and unexpected raw archive',async()=>{const {spawnSync}=await import('node:child_process');const dir=await mkdtemp(join(tmpdir(),'web-package-'));try{const input=join(dir,'in');await mkdir(input);await writeFile(join(input,'dictionary.json'),JSON.stringify(dataset([entry('かな')])));await writeFile(join(input,'archive.jsonl'),'');const out=join(dir,'out');await buildWeb(input,out);const app=join(out,'web/app.mjs');const original=await readFile(app);await writeFile(app,'stale source');let run=spawnSync('python3',['package-site.py',out,join(input,'dictionary.json'),join(dir,'release')],{encoding:'utf8'});assert.notEqual(run.status,0);assert.match(run.stderr,/source|stale/);await writeFile(app,original);await writeFile(join(out,'archive.jsonl'),'raw');run=spawnSync('python3',['package-site.py',out,join(input,'dictionary.json'),join(dir,'release')],{encoding:'utf8'});assert.notEqual(run.status,0);assert.match(run.stderr,/unexpected|allowlist/);}finally{await rm(dir,{recursive:true,force:true})}});

test('reuse published dictionary preserves every byte and rejects tampered shard',async()=>{
 const {rebuildWebFromPublished}=await import('./build-web.mjs');assert.equal(typeof rebuildWebFromPublished,'function');
 const {spawnSync}=await import('node:child_process');const dir=await mkdtemp(join(tmpdir(),'web-reuse-'));
 try{const input=join(dir,'in');await mkdir(input);await writeFile(join(input,'dictionary.json'),JSON.stringify(dataset([entry('かな')])));await writeFile(join(input,'archive.jsonl'),'');const base=join(dir,'base');const {version}=await buildWeb(input,base);
 const release=join(dir,'release');const packed=spawnSync('python3',['package-site.py',base,join(input,'dictionary.json'),release],{encoding:'utf8'});assert.equal(packed.status,0,packed.stderr);const manifest=JSON.parse(await readFile(join(release,'site-manifest.json'),'utf8'));
 const out=join(dir,'rebuilt');await rebuildWebFromPublished({siteDir:base,releaseManifest:manifest,outputDir:out});assert.deepEqual(await readFile(join(out,'data',version,'00.json')),await readFile(join(base,'data',version,'00.json')));
 assert.equal(JSON.parse(await readFile(join(out,'build-info.json'),'utf8')).dictionarySha256,manifest.dictionarySha256);assert.ok((await readdir(join(out,'web'))).includes('battle-app.mjs'));
 await writeFile(join(base,'data',version,'00.json'),'tampered');await assert.rejects(rebuildWebFromPublished({siteDir:base,releaseManifest:manifest,outputDir:join(dir,'bad')}),/mismatch/);
 }finally{await rm(dir,{recursive:true,force:true});}
});
test('new battle page versions stylesheet URL to avoid prior dictionary CSS cache',async()=>{
 const html=await readFile(new URL('./web/index.html',import.meta.url),'utf8');assert.match(html,/href="\.\/web\/styles\.css\?v=[a-zA-Z0-9-]+"/);
});
test('meaning release versions both changed entrypoints and grouping dependencies',async()=>{
 const token='20261005-meaning1';const html=await readFile(new URL('./web/index.html',import.meta.url),'utf8');
 for(const file of ['app.mjs','battle-app.mjs']){assert.ok(html.includes(`src="./web/${file}?v=${token}"`),file+' entrypoint must bypass prior cache');const source=await readFile(new URL('./web/'+file,import.meta.url),'utf8');assert.ok(source.includes(`'./candidate-groups.mjs?v=${token}'`));}
 const groups=await readFile(new URL('./web/candidate-groups.mjs',import.meta.url),'utf8');assert.ok(groups.includes(`'./meaning-equivalences.mjs?v=${token}'`));
});
