import {normalizeReading,createDictionary} from '../dictionary.mjs';import {bucketForReading} from '../reading-bucket.mjs';
const pendingLabels=new Set(['classification-conflict']);
export function createDictionaryClient({manifestUrl,fetchImpl=fetch}){
  const base=new URL(manifestUrl,globalThis.location?.href);let manifestPromise;
  const cache=new Map();
  async function request(url){const response=await fetchImpl(url);if(!response.ok)throw new Error('辞書の取得に失敗しました ('+response.status+')');return response;}
  async function manifest(){if(!manifestPromise)manifestPromise=(async()=>{const data=await (await request(base.href)).json();if(data.schemaVersion!==1||typeof data.version!=='string'||!data.shards)throw new Error('辞書の形式が一致しません');return data;})().catch(error=>{manifestPromise=null;throw error});return manifestPromise;}
  async function load(key,m){if(!cache.has(key)){const promise=(async()=>{const descriptor=m.shards[key];if(!descriptor||!/^([a-f0-9]{64})$/.test(descriptor.sha256)||!Number.isSafeInteger(descriptor.bytes))throw new Error('辞書の索引が不正です');const url=new URL(descriptor.url,base);if(url.origin!==base.origin||!url.pathname.startsWith(new URL('.',base).pathname))throw new Error('辞書の参照先が不正です');const bytes=await (await request(url.href)).arrayBuffer();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==descriptor.sha256||bytes.byteLength!==descriptor.bytes)throw new Error('辞書データの検証に失敗しました');const shard=JSON.parse(new TextDecoder().decode(bytes));if(shard.schemaVersion!==1||shard.version!==m.version||!Array.isArray(shard.review))throw new Error('辞書の版が一致しません');return {dictionary:createDictionary(shard.dataset),review:shard.review};})().catch(error=>{cache.delete(key);throw error});cache.set(key,promise);}return cache.get(key);}
  return Object.freeze({async search(input){const reading=normalizeReading(input);if(reading===null)return {reading:null,status:'invalid-reading',candidates:[],review:[]};const m=await manifest();const shard=await load(await bucketForReading(reading),m);const result=shard.dictionary.lookup(reading);const review=shard.review.filter(x=>x.reading===reading);const candidates=result.candidates;const status=candidates.some(c=>c.eligible)?'eligible':review.length||candidates.some(c=>c.labels.some(label=>pendingLabels.has(label)))?'pending':candidates.length?'ineligible':'unconfirmed';return {reading,status,candidates,review,sources:m.sources??[],version:m.version};}});
}
